---
- hosts: all
  gather_facts: false
  #ignore_errors: true
  tasks:
    - name: Check the date
      command: dateookl
      ignore_errors: true
    - name: Check uptime
      command: |
       uptime
       date
       nproc